name: "awake-action"
description: "Keep your free server awake"
author: "devpolo"
branding:
  icon: "arrow-right"
  color: "green"
inputs:
  url:
    description: "url to keep awake"
    required: true
outputs:
  result:
    description: "The result returned by the URL"
runs:
  using: "node12"
  main: "dist/index.js"
